language: python

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

matrix:
  include:
    - python: 3.6
      env: PANDAS=0.23.4

before_install:
  - pip install -U pip
  - pip install wheel

install:
  - pip install numpy
  - pip install -r test_requirements.test.txt
  - pip install pandas==$PANDAS

script: 
  - py.test grumpy/ --cov grumpy  -v --cov-report term-missing

after_success:
  - coveralls

